(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.Leksandsdorren_symbol_cmykepsResurser = function() {
	this.initialize(img.Leksandsdorren_symbol_cmykepsResurser);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,233,290);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Lager_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape.setTransform(179.6,115.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#245B8F").s().p("AgMAPQgHgGAAgJQABgHAFgGQAGgGAHAAQAKAAAFAFQAFAFgBAJIAAADIgbAAQABAJALAAQAHAAAHgEIgBAJQgGADgIAAQgKAAgFgFgAAKgCQAAgFgDgCQgCgCgFAAQgHAAgCAJIATAAIAAAAg");
	this.shape_1.setTransform(175.8,116.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#245B8F").s().p("AACAhIAAgIIAGAAIAAgRQAAgDgBgBQgBgBAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAQgEAAgFAEIAAATIAGAAIAAAIIgWAAIAAgIIAGAAIAAgwIgGAAIAAgJIAQAAIAAAgQAHgGAGAAQAGAAADAEQACACABAGIAAATIAGAAIAAAIg");
	this.shape_2.setTransform(171.1,115.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#245B8F").s().p("AgQAYQgDgCABgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAIAAACIAGABQAFAAACgDQACgDAAgEIAAgGQgFAFgGAAQgHAAgFgFQgGgFAAgIQAAgIAGgHQAFgFAIAAQAFAAAFAEIAAgDIAPAAIAAAIIgFAAIAAAeQgBAIgDAEQgFAGgIAAQgMAAgEgFgAgIgRQgDAEAAAFQAAAFADADQADACAEAAQAEAAAEgDIAAgPQgEgDgEAAQgEAAgDACg");
	this.shape_3.setTransform(166,117.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#245B8F").s().p("AgQAYQgCgCgBgDQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAIAAACIAGABQAEAAADgDQACgDAAgEIAAgGQgFAFgFAAQgIAAgFgFQgFgFAAgIQAAgIAFgHQAFgFAIAAQAFAAAFAEIAAgDIAQAAIAAAIIgHAAIAAAeQABAIgEAEQgFAGgJAAQgLAAgEgFgAgJgRQgDAEAAAFQAAAFADADQAEACAEAAQADAAAFgDIAAgPQgEgDgEAAQgEAAgEACg");
	this.shape_4.setTransform(161,117.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#245B8F").s().p("AgSAbQgDgCAAgDQAAgFAFAAQADAAACADIADgCIABgDIADgGIgNgcIgGAAIAAgJIAVAAIAAAIIgGAAIAIAUIAKgUIgHAAIAAgIIAVAAIAAAJIgGAAIgSAmIgCAFQgEAFgHAAQgDAAgCgCg");
	this.shape_5.setTransform(156.1,117.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQAEAAABACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgEAAgCgDQgFABgCAHIAAAOIAGAAIAAAIg");
	this.shape_6.setTransform(151.9,116.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape_7.setTransform(148.1,115.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#245B8F").s().p("AgVAoIAkhSIAIADIgkBSg");
	this.shape_8.setTransform(144.3,116.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAJAAQAIAAAGAFQAEAFABAJIgBADIgbAAQABAJALAAQAHAAAHgEIAAAJQgHADgJAAQgIAAgHgFgAAKgCQAAgFgCgCQgEgCgDAAQgIAAgBAJIASAAIAAAAg");
	this.shape_9.setTransform(139.7,116.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#245B8F").s().p("AgHATIgHgEQgCgCAAgDQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIADABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAGABQAIAAAAgEQAAgDgIgCIgLgEQgDgDgBgEQAAgGAFgDQAEgDAGgBIAIABIAGAEQACACAAADQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgFAAAAgFIAAgCIgGgBQgBABgDABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABIAFABIALAEQAEACAAAFQAAAHgFADQgFADgHABIgHgCg");
	this.shape_10.setTransform(135.4,116.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#245B8F").s().p("AgEAFQgCgCAAgDQAAgCACgCQACgCACAAQADAAACACQADACgBACQABADgDACQgCACgDAAQgCAAgCgCg");
	this.shape_11.setTransform(132.2,117.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#245B8F").s().p("AADAUIAAgIIAFAAIAAgQIgBgDQgCgDgDAAQgEAAgFAEIAAASIAFAAIAAAIIgUAAIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAGQAIgHAFAAQAHAAADAFQACADAAAFIAAASIAGAAIAAAIg");
	this.shape_12.setTransform(128.6,116.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAIAAQAKAAAFAFQAEAFAAAJIAAADIgbAAQACAJAKAAQAHAAAHgEIAAAJQgHADgJAAQgJAAgGgFgAAKgCQAAgFgCgCQgDgCgFAAQgHAAgBAJIASAAIAAAAg");
	this.shape_13.setTransform(123.7,116.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape_14.setTransform(119.7,115.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQAEAAABACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQgDAAgCgDQgFABgCAHIAAAOIAGAAIAAAIg");
	this.shape_15.setTransform(116.3,116.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAIAAQAKAAAFAFQAEAFAAAJIAAADIgbAAQACAJAKAAQAHAAAHgEIAAAJQgHADgJAAQgJAAgGgFgAAKgCQAAgFgCgCQgDgCgFAAQgHAAgBAJIASAAIAAAAg");
	this.shape_16.setTransform(112,116.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#245B8F").s().p("AgVAdIAAgIIAFAAIAAgoIgFAAIAAgIIAOAAIAAAEQAGgFAGAAQAHAAAFAGQAGAGAAAIQAAAIgGAGQgGAGgHAAQgFAAgFgEIAAANIAGAAIAAAIgAgGgPIAAAPQAFAEADAAQAEAAADgEQAEgCAAgGQgBgFgDgDQgDgDgEAAQgDAAgFAEg");
	this.shape_17.setTransform(107.3,117.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#245B8F").s().p("AADAUIAAgIIAFAAIgIgIIgHAIIAEAAIAAAIIgTAAIAAgJIAGAAIALgLIgLgKIgFAAIAAgJIAUAAIAAAIIgFAAIAGAIIAIgIIgGAAIAAgIIAUAAIAAAJIgFAAIgMAKIANALIAFAAIAAAJg");
	this.shape_18.setTransform(102.4,116.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#245B8F").s().p("AgMAPQgHgGABgJQAAgHAFgGQAFgGAIAAQAKAAAFAFQAFAFgBAJIAAADIgbAAQACAJAKAAQAHAAAHgEIgBAJQgGADgJAAQgIAAgGgFgAAKgCQAAgFgCgCQgEgCgEAAQgHAAgCAJIATAAIAAAAg");
	this.shape_19.setTransform(97.7,116.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQAAAAABABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape_20.setTransform(93.7,115.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAPAAIAAAJQAFgKAGAAQADAAADACQAAAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQgDAAgCgDQgFABgCAHIAAAOIAGAAIAAAIg");
	this.shape_21.setTransform(90.3,116.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#245B8F").s().p("AgOAOQgGgFAAgJQAAgHAGgGQAFgGAJAAQAKAAAFAGQAGAFAAAIQAAAIgGAGQgFAGgKAAQgJAAgFgGgAgHgIQgDAEAAAEQAAAFADAEQADADAEAAQAFAAADgDQADgEAAgFQAAgEgDgEQgDgDgFAAQgEAAgDADg");
	this.shape_22.setTransform(85.9,116.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#245B8F").s().p("AgWAdIAAgIIAGAAIAAgoIgGAAIAAgIIAPAAIAAAEQAGgFAFAAQAIAAAFAGQAGAGgBAIQABAIgGAGQgFAGgJAAQgEAAgFgEIAAANIAGAAIAAAIgAgGgPIAAAPQAEAEAEAAQAEAAADgEQAEgCgBgGQAAgFgCgDQgDgDgFAAQgEAAgEAEg");
	this.shape_23.setTransform(81,117.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#245B8F").s().p("AgMAPQgHgGAAgJQABgHAFgGQAGgGAHAAQAKAAAFAFQAFAFgBAJIAAADIgbAAQABAJALAAQAHAAAHgEIgBAJQgGADgJAAQgIAAgGgFgAAKgCQAAgFgDgCQgCgCgFAAQgHAAgCAJIATAAIAAAAg");
	this.shape_24.setTransform(76.2,116.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#245B8F").s().p("AgQAYQgDgCABgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAABAAIgBACIAGABQAFAAACgDQACgDAAgEIAAgGQgFAFgGAAQgHAAgFgFQgGgFAAgIQAAgIAGgHQAFgFAIAAQAFAAAFAEIAAgDIAPAAIAAAIIgFAAIAAAeQgBAIgDAEQgFAGgIAAQgMAAgEgFgAgIgRQgDAEAAAFQAAAFADADQADACAEAAQAEAAAEgDIAAgPQgEgDgEAAQgEAAgDACg");
	this.shape_25.setTransform(71.5,117.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#245B8F").s().p("AgQASQgEgDAAgGQAAgFAFgDQAEgCAHAAIAJABIAAgEQAAgDgBgCQgDgDgEAAIgEABIAAACQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgEAEgDQAEgDAIAAQAIAAAFAFQADAEAAAGIAAAQIAGAAIAAAIIgQAAIAAgFQgFAFgHAAQgFAAgEgCgAgKAJQAAAEAGAAQAEAAAFgDIAAgGIgHgBQgIAAAAAGg");
	this.shape_26.setTransform(66.8,116.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQADAAACACQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgFAAgBgDQgFABgCAHIAAAOIAGAAIAAAIg");
	this.shape_27.setTransform(62.6,116.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#245B8F").s().p("AgQASQgEgDAAgGQAAgFAFgDQAEgCAHAAIAJABIAAgEQAAgDgBgCQgDgDgEAAIgEABIAAACQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgEAEgDQAEgDAIAAQAIAAAFAFQADAEAAAGIAAAQIAGAAIAAAIIgQAAIAAgFQgFAFgHAAQgFAAgEgCgAgKAJQAAAEAGAAQAEAAAFgDIAAgGIgHgBQgIAAAAAGg");
	this.shape_28.setTransform(58.3,116.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#245B8F").s().p("AgQAYQgDgCABgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAIAAACIAGABQAFAAACgDQACgDAAgEIAAgGQgFAFgGAAQgHAAgFgFQgGgFAAgIQAAgIAGgHQAFgFAIAAQAFAAAFAEIAAgDIAPAAIAAAIIgFAAIAAAeQgBAIgDAEQgFAGgIAAQgMAAgEgFgAgIgRQgDAEAAAFQAAAFADADQADACAEAAQAEAAAEgDIAAgPQgEgDgEAAQgEAAgDACg");
	this.shape_29.setTransform(53.5,117.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#245B8F").s().p("AgQAfQgEgDAAgFQAAgGAFgDQAEgDAHAAIAJABIAAgDQAAgEgBgBQgDgDgEAAIgEAAIAAACQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgDAEgDQAEgDAIAAQAIAAAFAFQADADAAAGIAAARIAGAAIAAAIIgQAAIAAgEQgFAFgHAAQgFAAgEgDgAgKAWQAAAFAGAAQAEAAAFgEIAAgGIgHgBQgIAAAAAGgAgJgNQgDgDAAgFQAAgFADgEQAEgDAFAAQAEAAADADQAEAEAAAFQAAAFgEADQgDAEgEAAQgFAAgEgEgAgDgZQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIACAEQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAgBQABAAAAAAIACgEQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_30.setTransform(46.8,115.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#245B8F").s().p("AgWAdIAAgIIAGAAIAAgoIgGAAIAAgIIAQAAIAAAEQAFgFAFAAQAIAAAFAGQAFAGAAAIQAAAIgFAGQgFAGgJAAQgEAAgFgEIAAANIAGAAIAAAIgAgGgPIAAAPQAFAEADAAQAFAAACgEQADgCABgGQgBgFgCgDQgEgDgEAAQgDAAgFAEg");
	this.shape_31.setTransform(42,117.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQADAAACACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgEAAgCgDQgFABgCAHIAAAOIAGAAIAAAIg");
	this.shape_32.setTransform(35.7,116.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAJAAQAJAAAFAFQAEAFAAAJIAAADIgbAAQABAJALAAQAHAAAHgEIAAAJQgHADgJAAQgIAAgHgFgAAKgCQAAgFgCgCQgEgCgDAAQgIAAgBAJIASAAIAAAAg");
	this.shape_33.setTransform(31.4,116.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#245B8F").s().p("AAPAUIAAgIIAEAAIAAgQIAAgDQgBgDgDAAQgFAAgFAEIAAASIAFAAIAAAIIgUAAIAAgIIAGAAIAAgQIgBgDQgBgDgEAAQgEAAgFAEIAAASIAFAAIAAAIIgVAAIAAgIIAGAAIAAgWIgGAAIAAgIIAPAAIAAAGQAHgHAHAAQAGAAACAEIACACQAGgGAGAAQAJAAADAFQACAEAAAEIAAASIAFAAIAAAIg");
	this.shape_34.setTransform(25.5,116.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#245B8F").s().p("AgIATIgGgEQgCgCAAgDQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIADABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAGABQAIAAAAgEQAAgDgIgCIgLgEQgEgDAAgEQAAgGAFgDQAEgDAGgBIAIABIAGAEQACACAAADQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgFAAAAgFIAAgCIgGgBQgBABgCABQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQAAAAABABIAFABIALAEQAEACAAAFQAAAHgFADQgEADgIABIgIgCg");
	this.shape_35.setTransform(17.6,116.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#245B8F").s().p("AgQAbQgEgDAAgGQAAgFAFgDQAEgDAHAAIAJABIAAgEQAAgDgBgBQgDgCgEAAIgEAAIAAACQAAAAAAAAQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAAAAAAAQAAgEAEgDQAEgDAIAAQAIAAAFAFQADAEAAAFIAAARIAGAAIAAAIIgQAAIAAgEQgFAEgHAAQgFABgEgDgAgKASQAAAFAGgBQAEAAAFgDIAAgGIgHgBQgIAAAAAGgAAEgRQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgAgOgRQgBgBAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgDAAgCgBg");
	this.shape_36.setTransform(13.4,115.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#245B8F").s().p("AgUAeIAAgJIAGAAIAAgpIgGAAIAAgJIAXAAIAAAJIgGAAIAAApIAOAAIAAgJIAKAAIAAASg");
	this.shape_37.setTransform(8.6,115.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#245B8F").s().p("AAGAQQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBgBAAIgDgJIgCAJQAAAAgBABQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAgBIAIgGIgKgBQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAAAgBgBQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAIAJAFIgDgJQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAAAABAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAABIgDAJIAIgFQADgCACABQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABABABQAAAAgBABQAAABAAAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAIgKABIAIAGQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgCABIgCgBg");
	this.shape_38.setTransform(4.1,113.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#245B8F").s().p("AgfBMQABgOAGgGQAIgGARAAQARAAAHAGQAGAGAAAOQAAAZgeAAQgfAAgBgZgAgbAqIgEiOIA/AAIgFCOg");
	this.shape_39.setTransform(162.8,93.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhBAAIAAjFIBTAAQBIAAAABAQAAATgGAMQgGAJgNAJIAeBUgAgPgHIAIAAQAHAAACgEQADgFAAgLQAAgTgMAAIgIAAg");
	this.shape_40.setTransform(148.3,93.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhBAAIAAjFIBTAAQBIAAAABAQAAATgGAMQgGAJgNAJIAeBUgAgPgHIAIAAQAHAAACgEQADgFAAgLQAAgTgMAAIgIAAg");
	this.shape_41.setTransform(130.3,93.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#245B8F").s().p("AhGBjQgUgZAAg1QAAg0AVgYQAVgZAwAAQAxAAAWAZQAUAXAAAzQAAA3gVAYQgWAbgwAAQgvgBgXgZgAgRgQQgDAHAAAaIAAAOQAAAbADAHQAFAJANAAQAOAAAEgIQADgIAAgaIAAgPQAAgZgEgIQgEgJgOAAQgNAAgEAJgAAEhoQAAgTAXgBQAYABABATQgBAVgYAAQgXAAAAgVgAg0hoQAAgTAYgBQAYABgBATQABAVgYAAQgYAAAAgVg");
	this.shape_42.setTransform(111.2,91);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#245B8F").s().p("AhVBjIAAjFIBPAAQAyAAAWAaQAUAWAAAvQAABmheAAgAgRAxIAIAAQAPAAAGgMQAEgKAAgaQAAgZgFgKQgFgMgQAAIgHAAg");
	this.shape_43.setTransform(92.2,93.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhBAAIAAjFIBTAAQBIAAAABAQABATgHAMQgGAJgNAJIAeBUgAgQgHIAJAAQAHAAACgEQADgFAAgLQAAgTgMAAIgJAAg");
	this.shape_44.setTransform(73.7,93.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#245B8F").s().p("AhBBjIAAjFICDAAIgFA0Ig6AAIAAAYIAyAAIAAAtIgyAAIAAAcIA/AAIgFAwg");
	this.shape_45.setTransform(57.4,93.2);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#245B8F").s().p("AgiBjIAAiPIgsAAIACg2ICbAAIgEA2IgqAAIAACPg");
	this.shape_46.setTransform(42,93.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#245B8F").s().p("AgiBjIAAiPIgsAAIACg2ICbAAIgEA2IgqAAIAACPg");
	this.shape_47.setTransform(26.8,93.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#245B8F").s().p("AgiBjIAAg/IgziGIBIAAIANBIIACAAIAOhIIBGAAIg1CGIAAA/g");
	this.shape_48.setTransform(10.6,93.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#245B8F").s().p("AhVBjIAAjFIBPAAQAyAAAWAaQAUAWAAAvQAABmheAAgAgRAxIAIAAQAPAAAGgMQAEgKAAgaQAAgZgFgKQgFgMgQAAIgHAAg");
	this.shape_49.setTransform(258.5,56);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#245B8F").s().p("AAXBjIgGgfIgjAAIgGAfIhBAAIApjFIBhAAIApDFgAAMAbIgMhBIAAAAIgNBBIAZAAg");
	this.shape_50.setTransform(239.6,56);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#245B8F").s().p("AhDBeIAEg2QArALAPAAQAJAAAAgHQAAgFgKgFIgTgIQgOgGgIgGQgagRAAgfQAAggATgRQATgTAjABQAgAAAlAGIgIA5QgogJgMABQgMAAAAAHQAAADADACIAJAEIATAIQANAGAIAGQAZAQAAAdQAABEhKAAQghAAgigJg");
	this.shape_51.setTransform(222.9,56);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#245B8F").s().p("AhDBeIAEg2QArALAPAAQAJAAAAgHQAAgFgKgFIgTgIQgOgGgIgGQgagRAAgfQAAggATgRQATgTAjABQAgAAAlAGIgIA5QgogJgMABQgMAAAAAHQAAADADACIAJAEIATAIQANAGAIAGQAZAQAAAdQAABEhKAAQghAAgigJg");
	this.shape_52.setTransform(207.4,56);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#245B8F").s().p("AAXBjIgHgfIgiAAIgGAfIhBAAIApjFIBhAAIApDFgAAMAbIgMhBIgBAAIgMBBIAZAAg");
	this.shape_53.setTransform(190.7,56);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#245B8F").s().p("Ag9BjIAAjFIBEAAIAACSIA3AAIgFAzg");
	this.shape_54.setTransform(176,56);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#245B8F").s().p("AAFBjIgThCIgDAAIAABCIhBAAIAAjFIBBAAIAABOIADAAIAYhOIBJAAIgpBmIAmBfg");
	this.shape_55.setTransform(160.5,56);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#245B8F").s().p("AhDBeIAEg2QArALAPAAQAJAAAAgHQAAgFgKgFIgTgIQgOgGgIgGQgagRAAgfQAAggATgRQATgTAjABQAgAAAlAGIgIA5QgogJgMABQgMAAAAAHQAAADADACIAJAEIATAIQANAGAIAGQAZAQAAAdQAABEhKAAQghAAgigJg");
	this.shape_56.setTransform(143.1,56);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#245B8F").s().p("AgiBjIAAiPIgsAAIACg2ICbAAIgEA2IgqAAIAACPg");
	this.shape_57.setTransform(127.8,56);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#245B8F").s().p("AhBBjIAAjFICDAAIgFA0Ig6AAIAAAYIAyAAIAAAtIgyAAIAAAcIA/AAIgFAwg");
	this.shape_58.setTransform(113.3,56);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#245B8F").s().p("AASBjIAAhGIgiAAIAABGIhEAAIAAjFIBEAAIAABKIAiAAIAAhKIBDAAIAADFg");
	this.shape_59.setTransform(95.7,56);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhCAAIAAjFIBUAAQBJAAAABAQgBATgGAMQgGAJgNAJIAdBUgAgQgHIAIAAQAIAAACgEQADgFAAgLQAAgTgMAAIgJAAg");
	this.shape_60.setTransform(77.2,56);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#245B8F").s().p("AhBBjIAAjFICCAAIgEA0Ig6AAIAAAYIAzAAIAAAtIgzAAIAAAcIA+AAIgEAwg");
	this.shape_61.setTransform(61,56);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#245B8F").s().p("AAFBjIgThCIgDAAIAABCIhCAAIAAjFIBCAAIAABOIADAAIAYhOIBKAAIgqBmIAmBfg");
	this.shape_62.setTransform(45.1,56);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#245B8F").s().p("AAXB7IgHgfIgiAAIgGAfIhBAAIAqjFIBgAAIApDFgAAMAzIgMhCIgBAAIgMBCIAZAAgAAEhmQAAgUAXAAQAYAAAAAUQAAAUgYAAQgXAAAAgUgAgzhmQAAgUAWAAQAYAAABAUQgBAUgYAAQgWAAAAgUg");
	this.shape_63.setTransform(26.5,53.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#245B8F").s().p("AhDBeIAEg2QArALAPAAQAJAAAAgHQAAgFgKgFIgTgIQgOgGgIgGQgagRAAgfQAAggATgRQATgTAjABQAgAAAlAGIgIA5QgogJgMABQgMAAAAAHQAAADADACIAJAEIATAIQANAGAIAGQAZAQAAAdQAABEhKAAQghAAgigJg");
	this.shape_64.setTransform(9.7,56);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#245B8F").s().p("AATBjIgnhOIgDAAIAABOIg8AAIAAjFIBDAAIAlBQIACAAIAAhQIA9AAIAADFg");
	this.shape_65.setTransform(129.7,18.8);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#245B8F").s().p("AhABjIAAjFICBAAIgEA0Ig6AAIAAAYIAyAAIAAAtIgyAAIAAAcIA+AAIgEAwg");
	this.shape_66.setTransform(113.1,18.8);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#245B8F").s().p("AAXBjIgGgfIgjAAIgGAfIhBAAIApjFIBhAAIApDFgAALAbIgLhBIAAAAIgNBBIAYAAg");
	this.shape_67.setTransform(90.2,18.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#245B8F").s().p("AhABjIAAjFICBAAIgEA0Ig6AAIAAAcIAsAAIAAAtIgsAAIAABIg");
	this.shape_68.setTransform(75,18.8);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#245B8F").s().p("AhBBjIAAjFICCAAIgEA0Ig6AAIAAAcIAsAAIAAAtIgsAAIAABIg");
	this.shape_69.setTransform(61,18.8);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#245B8F").s().p("AAXBjIgHgfIgiAAIgGAfIhBAAIApjFIBhAAIApDFgAAMAbIgMhBIgBAAIgMBBIAZAAg");
	this.shape_70.setTransform(44.1,18.8);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#245B8F").s().p("AAFBjIgThCIgDAAIAABCIhCAAIAAjFIBCAAIAABOIADAAIAYhOIBKAAIgqBmIAmBfg");
	this.shape_71.setTransform(27.1,18.8);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#245B8F").s().p("AhDBeIAEg2QArALAPAAQAJAAAAgHQAAgFgKgFIgTgIQgOgGgIgGQgagRAAgfQAAggATgSQATgSAjAAQAgAAAlAHIgIA4QgogHgMAAQgMgBAAAIQAAADADACIAJAEIATAIQANAFAIAHQAZAQAAAdQAABDhKAAQghAAgigIg");
	this.shape_72.setTransform(9.7,18.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,282,122.3), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Lager_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#325B8B").s().p("AyYAVIAAgpMAkwAAAIAAApg");
	this.shape.setTransform(89.9,83.6,0.764,0.764);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#325B8B").s().p("AgqClQgLgKAAgXQAAgXALgLQANgLAeAAQAfAAAMALQALALAAAYQAAAWgLAKQgNAMgeAAQgeAAgNgMgAgxBIIgGj4IBvAAIgID4g");
	this.shape_1.setTransform(173.5,65.3,0.764,0.764);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#325B8B").s().p("ABUCuIAAimIgDAAIghCmIhhAAIggimIgDAAIAACmIhpAAIANlbICWAAIAaCeIAEAAIAZieICUAAIANFbg");
	this.shape_2.setTransform(149.5,65,0.764,0.764);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#325B8B").s().p("AhyCuIAAlbIDlAAIgIBdIhmAAIAAAqIBZAAIAABPIhZAAIAAAwIBuAAIgIBVg");
	this.shape_3.setTransform(124.2,65,0.764,0.764);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#325B8B").s().p("AAfCuIAAh7Ig8AAIAAB7Ih3AAIAAlbIB3AAIAACCIA8AAIAAiCIB2AAIAAFbg");
	this.shape_4.setTransform(100.6,65,0.764,0.764);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#325B8B").s().p("Ag8CuIAAj8IhOAAIAFhfIEQAAIgHBfIhKAAIAAD8g");
	this.shape_5.setTransform(69.1,65,0.764,0.764);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#325B8B").s().p("Ag8CuIAAj8IhOAAIAFhfIEQAAIgHBfIhKAAIAAD8g");
	this.shape_6.setTransform(48.8,65,0.764,0.764);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#325B8B").s().p("Ag6CuIAAlbIB1AAIAAFbg");
	this.shape_7.setTransform(32.1,65,0.764,0.764);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#325B8B").s().p("AiWCuIAAlbICLAAQBXAAAoAuQAiAoABBRQAABTgkAsQgoA1haAAgAgeBXIAOAAQAbAAAKgWQAIgRgBguQABgtgJgSQgKgVgcAAIgMAAg");
	this.shape_8.setTransform(13.2,65,0.764,0.764);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#325B8B").s().p("AvZAYIAAgvIezAAIAAAvg");
	this.shape_9.setTransform(75.3,32.7,0.764,0.764);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#325B8B").s().p("AAoCuIgLg2Ig9AAIgMA2IhwAAIBIlbICqAAIBIFbgAgYAwIAtAAIgVh0IgCAAg");
	this.shape_10.setTransform(130.5,13.7,0.764,0.764);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#325B8B").s().p("AiVCuIAAlbICJAAQBYAAAoAuQAiAoAABRQAAC0ikAAgAgeBXIAOAAQAbAAAKgWQAHgRAAguQAAgtgIgSQgKgVgcAAIgMAAg");
	this.shape_11.setTransform(106,13.7,0.764,0.764);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#325B8B").s().p("AiVCuIAAlbICJAAQBYAAAoAuQAiAoAABRQAAC0ikAAgAgeBXIAOAAQAbAAAKgWQAHgRAAguQAAgtgIgSQgKgVgcAAIgMAAg");
	this.shape_12.setTransform(80.4,13.7,0.764,0.764);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#325B8B").s().p("Ag8CuIAAhvIhZjsIB+AAIAXCAIAEAAIAXiAIB7AAIhcDtIAABug");
	this.shape_13.setTransform(55.7,13.7,0.764,0.764);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#325B8B").s().p("AAJCuIgihzIgGAAIAABzIhyAAIAAlbIByAAIAACKIAGAAIAriKICAAAIhIC0IBDCng");
	this.shape_14.setTransform(33.5,13.7,0.764,0.764);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#325B8B").s().p("Ah3CkIAIheQBKASAbABQARgBAAgMQAAgFgFgFIgNgHIhJgjQgtgeAAg3QABg4AhgfQAigfA8AAQA5AABAALIgNBjQhJgOgSAAQgVAAAAANQAAAGAFADIAPAHQBAAcAHAHQArAcABA0QAAA6giAeQggAehAABQg5AAg+gQg");
	this.shape_15.setTransform(10.3,13.7,0.764,0.764);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,179.8,85.3), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Lager_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape.setTransform(179.6,94.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#245B8F").s().p("AgMAPQgHgGAAgJQABgHAFgGQAGgGAHAAQAKAAAFAFQAFAFgBAJIAAADIgbAAQABAJALAAQAHAAAHgEIgBAJQgGADgIAAQgKAAgFgFgAAKgCQAAgFgDgCQgCgCgFAAQgHAAgCAJIATAAIAAAAg");
	this.shape_1.setTransform(175.8,95.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#245B8F").s().p("AACAhIAAgIIAGAAIAAgRQAAgDgBgBQgBgBAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAQgEAAgFAEIAAATIAGAAIAAAIIgWAAIAAgIIAGAAIAAgwIgGAAIAAgJIAQAAIAAAgQAHgGAGAAQAGAAADAEQACACABAGIAAATIAGAAIAAAIg");
	this.shape_2.setTransform(171.1,94);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#245B8F").s().p("AgQAYQgDgCABgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAABIAGABQAFAAACgDQACgDAAgEIAAgGQgFAFgGAAQgHAAgFgFQgGgFAAgIQAAgIAGgHQAFgFAIAAQAFAAAFAEIAAgDIAPAAIAAAIIgFAAIAAAeQgBAIgDAEQgFAGgIAAQgMAAgEgFgAgIgRQgDAEAAAFQAAAFADADQADACAEAAQAEAAAEgDIAAgPQgEgDgEAAQgEAAgDACg");
	this.shape_3.setTransform(166,96.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#245B8F").s().p("AgQAYQgCgCgBgDQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAABIAGABQAEAAADgDQACgDAAgEIAAgGQgFAFgFAAQgIAAgFgFQgFgFAAgIQAAgIAFgHQAFgFAIAAQAFAAAFAEIAAgDIAQAAIAAAIIgHAAIAAAeQABAIgEAEQgFAGgJAAQgLAAgEgFgAgJgRQgDAEAAAFQAAAFADADQAEACAEAAQADAAAFgDIAAgPQgEgDgEAAQgEAAgEACg");
	this.shape_4.setTransform(161,96.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#245B8F").s().p("AgSAbQgDgCAAgDQAAgFAFAAQADAAACADIADgCIABgDIADgGIgNgcIgGAAIAAgJIAVAAIAAAIIgGAAIAIAUIAKgUIgHAAIAAgIIAVAAIAAAJIgGAAIgSAmIgCAFQgEAFgHAAQgDAAgCgCg");
	this.shape_5.setTransform(156.1,96.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQAEAAABACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgEAAgCgDQgFABgCAGIAAAPIAGAAIAAAIg");
	this.shape_6.setTransform(151.9,95.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape_7.setTransform(148.1,94.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#245B8F").s().p("AgVAoIAkhSIAIAEIgkBRg");
	this.shape_8.setTransform(144.3,94.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAJAAQAIAAAGAFQAEAFABAJIgBADIgbAAQABAJALAAQAHAAAHgEIAAAJQgHADgJAAQgIAAgHgFgAAKgCQAAgFgCgCQgEgCgDAAQgIAAgBAJIASAAIAAAAg");
	this.shape_9.setTransform(139.7,95.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#245B8F").s().p("AgHATIgHgEQgCgCAAgDQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIADABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAGABQAIAAAAgEQAAgDgIgCIgLgEQgDgDgBgEQAAgFAFgEQAEgDAGgBIAIABIAGAEQACACAAADQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgFAAAAgFIAAgCIgGAAQgBgBgDACQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABIAFACIALADQAEADAAAEQAAAHgFADQgFAEgHAAIgHgCg");
	this.shape_10.setTransform(135.4,95.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#245B8F").s().p("AgEAFQgCgCAAgDQAAgCACgCQACgCACAAQADAAACACQADACgBACQABADgDACQgCACgDAAQgCAAgCgCg");
	this.shape_11.setTransform(132.2,96.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#245B8F").s().p("AADAUIAAgIIAFAAIAAgQIgBgDQgCgDgDAAQgEAAgFAEIAAASIAFAAIAAAIIgUAAIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAGQAIgHAFAAQAHAAADAFQACADAAAFIAAASIAGAAIAAAIg");
	this.shape_12.setTransform(128.6,95.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAIAAQAKAAAFAFQAEAFAAAJIAAADIgbAAQACAJAKAAQAHAAAHgEIAAAJQgHADgJAAQgJAAgGgFgAAKgCQAAgFgCgCQgDgCgFAAQgHAAgBAJIASAAIAAAAg");
	this.shape_13.setTransform(123.7,95.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQABAAAAABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape_14.setTransform(119.7,94.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQAEAAABACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQgDAAgCgDQgFABgCAGIAAAPIAGAAIAAAIg");
	this.shape_15.setTransform(116.3,95.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAIAAQAKAAAFAFQAEAFAAAJIAAADIgbAAQACAJAKAAQAHAAAHgEIAAAJQgHADgJAAQgJAAgGgFgAAKgCQAAgFgCgCQgDgCgFAAQgHAAgBAJIASAAIAAAAg");
	this.shape_16.setTransform(112,95.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#245B8F").s().p("AgVAdIAAgIIAFAAIAAgoIgFAAIAAgIIAOAAIAAAEQAGgFAGAAQAHAAAFAGQAGAGAAAIQAAAIgGAGQgGAGgHAAQgFAAgFgEIAAANIAGAAIAAAIgAgGgPIAAAPQAFAEADAAQAEAAADgEQAEgCAAgGQgBgFgDgDQgDgDgEAAQgDAAgFAEg");
	this.shape_17.setTransform(107.3,96.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#245B8F").s().p("AADAUIAAgIIAFAAIgIgIIgHAIIAEAAIAAAIIgTAAIAAgJIAGAAIALgLIgLgKIgFAAIAAgJIAUAAIAAAIIgFAAIAGAIIAIgIIgGAAIAAgIIAUAAIAAAJIgFAAIgMAKIANALIAFAAIAAAJg");
	this.shape_18.setTransform(102.4,95.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#245B8F").s().p("AgMAPQgHgGABgJQAAgHAFgGQAFgGAIAAQAKAAAFAFQAFAFgBAJIAAADIgbAAQACAJAKAAQAHAAAHgEIgBAJQgGADgJAAQgIAAgGgFgAAKgCQAAgFgCgCQgEgCgEAAQgHAAgCAJIATAAIAAAAg");
	this.shape_19.setTransform(97.7,95.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#245B8F").s().p("AgFAVQgBgCAAgEIAAgTIgIAAIAAgJIAIAAIAAgIIAIgEIAAAMIAMAAIAAAJIgMAAIAAARIABADQAAAAABABQAAAAABAAQAAABABAAQAAAAABAAQADAAAFgCIgBAIQgFACgEAAQgHAAgDgFg");
	this.shape_20.setTransform(93.7,94.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAPAAIAAAJQAFgKAGAAQADAAADACQAAAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQgDAAgCgDQgFABgCAGIAAAPIAGAAIAAAIg");
	this.shape_21.setTransform(90.3,95.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#245B8F").s().p("AgOAOQgGgFAAgJQAAgHAGgGQAFgGAJAAQAKAAAFAGQAGAFAAAIQAAAIgGAGQgFAGgKAAQgJAAgFgGgAgHgIQgDAEAAAEQAAAFADAEQADADAEAAQAFAAADgDQADgEAAgFQAAgEgDgEQgDgDgFAAQgEAAgDADg");
	this.shape_22.setTransform(85.9,95.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#245B8F").s().p("AgWAdIAAgIIAGAAIAAgoIgGAAIAAgIIAPAAIAAAEQAGgFAFAAQAIAAAFAGQAGAGgBAIQABAIgGAGQgFAGgJAAQgEAAgFgEIAAANIAGAAIAAAIgAgGgPIAAAPQAEAEAEAAQAEAAADgEQAEgCgBgGQAAgFgCgDQgDgDgFAAQgEAAgEAEg");
	this.shape_23.setTransform(81,96.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#245B8F").s().p("AgMAPQgHgGAAgJQABgHAFgGQAGgGAHAAQAKAAAFAFQAFAFgBAJIAAADIgbAAQABAJALAAQAHAAAHgEIgBAJQgGADgJAAQgIAAgGgFgAAKgCQAAgFgDgCQgCgCgFAAQgHAAgCAJIATAAIAAAAg");
	this.shape_24.setTransform(76.2,95.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#245B8F").s().p("AgQAYQgDgCABgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAABABIgBABIAGABQAFAAACgDQACgDAAgEIAAgGQgFAFgGAAQgHAAgFgFQgGgFAAgIQAAgIAGgHQAFgFAIAAQAFAAAFAEIAAgDIAPAAIAAAIIgFAAIAAAeQgBAIgDAEQgFAGgIAAQgMAAgEgFgAgIgRQgDAEAAAFQAAAFADADQADACAEAAQAEAAAEgDIAAgPQgEgDgEAAQgEAAgDACg");
	this.shape_25.setTransform(71.5,96.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#245B8F").s().p("AgQASQgEgDAAgGQAAgFAFgDQAEgCAHAAIAJABIAAgEQAAgDgBgCQgDgDgEAAIgEABIAAACQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgEAEgDQAEgDAIAAQAIAAAFAFQADAEAAAGIAAAQIAGAAIAAAIIgQAAIAAgFQgFAFgHAAQgFAAgEgCgAgKAJQAAAEAGAAQAEAAAFgDIAAgGIgHgBQgIAAAAAGg");
	this.shape_26.setTransform(66.8,95.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQADAAACACQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgFAAgBgDQgFABgCAGIAAAPIAGAAIAAAIg");
	this.shape_27.setTransform(62.6,95.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#245B8F").s().p("AgQASQgEgDAAgGQAAgFAFgDQAEgCAHAAIAJABIAAgEQAAgDgBgCQgDgDgEAAIgEABIAAACQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgEAEgDQAEgDAIAAQAIAAAFAFQADAEAAAGIAAAQIAGAAIAAAIIgQAAIAAgFQgFAFgHAAQgFAAgEgCgAgKAJQAAAEAGAAQAEAAAFgDIAAgGIgHgBQgIAAAAAGg");
	this.shape_28.setTransform(58.3,95.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#245B8F").s().p("AgQAYQgDgCABgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAABIAGABQAFAAACgDQACgDAAgEIAAgGQgFAFgGAAQgHAAgFgFQgGgFAAgIQAAgIAGgHQAFgFAIAAQAFAAAFAEIAAgDIAPAAIAAAIIgFAAIAAAeQgBAIgDAEQgFAGgIAAQgMAAgEgFgAgIgRQgDAEAAAFQAAAFADADQADACAEAAQAEAAAEgDIAAgPQgEgDgEAAQgEAAgDACg");
	this.shape_29.setTransform(53.5,96.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#245B8F").s().p("AgQAfQgEgDAAgFQAAgGAFgDQAEgDAHAAIAJABIAAgDQAAgEgBgBQgDgDgEAAIgEAAIAAACQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgDAEgDQAEgDAIAAQAIAAAFAFQADADAAAGIAAARIAGAAIAAAIIgQAAIAAgEQgFAFgHAAQgFAAgEgDgAgKAWQAAAFAGAAQAEAAAFgEIAAgGIgHgBQgIAAAAAGgAgJgNQgDgDAAgFQAAgFADgEQAEgDAFAAQAEAAADADQAEAEAAAFQAAAFgEADQgDAEgEAAQgFAAgEgEgAgDgZQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIACAEQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAgBQABAAAAAAIACgEQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_30.setTransform(46.8,93.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#245B8F").s().p("AgWAdIAAgIIAGAAIAAgoIgGAAIAAgIIAQAAIAAAEQAFgFAFAAQAIAAAFAGQAFAGAAAIQAAAIgFAGQgFAGgJAAQgEAAgFgEIAAANIAGAAIAAAIgAgGgPIAAAPQAFAEADAAQAFAAACgEQADgCABgGQgBgFgCgDQgEgDgEAAQgDAAgFAEg");
	this.shape_31.setTransform(42,96.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#245B8F").s().p("AgQAUIAAgIIAFAAIAAgWIgFAAIAAgIIAOAAIAAAJQAGgKAGAAQADAAACACQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgEAAgCgDQgFABgCAGIAAAPIAGAAIAAAIg");
	this.shape_32.setTransform(35.7,95.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#245B8F").s().p("AgNAPQgFgGAAgJQgBgHAGgGQAFgGAJAAQAJAAAFAFQAEAFAAAJIAAADIgbAAQABAJALAAQAHAAAHgEIAAAJQgHADgJAAQgIAAgHgFgAAKgCQAAgFgCgCQgEgCgDAAQgIAAgBAJIASAAIAAAAg");
	this.shape_33.setTransform(31.4,95.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#245B8F").s().p("AAPAUIAAgIIAEAAIAAgQIAAgDQgBgDgDAAQgFAAgFAEIAAASIAFAAIAAAIIgUAAIAAgIIAGAAIAAgQIgBgDQgBgDgEAAQgEAAgFAEIAAASIAFAAIAAAIIgVAAIAAgIIAGAAIAAgWIgGAAIAAgIIAPAAIAAAGQAHgHAHAAQAGAAACAEIACACQAGgGAGAAQAJAAADAFQACADAAAFIAAASIAFAAIAAAIg");
	this.shape_34.setTransform(25.5,95.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#245B8F").s().p("AgIATIgGgEQgCgCAAgDQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIADABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAAACIAGABQAIAAAAgEQAAgDgIgCIgLgEQgEgDAAgEQAAgFAFgEQAEgDAGgBIAIABIAGAEQACACAAADQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgFAAAAgFIAAgCIgGAAQgBgBgCACQgBAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQAAAAABABIAFACIALADQAEADAAAEQAAAHgFADQgEAEgIAAIgIgCg");
	this.shape_35.setTransform(17.6,95.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#245B8F").s().p("AgQAbQgEgDAAgFQAAgGAFgDQAEgDAHAAIAJABIAAgEQAAgDgBgBQgDgCgEgBIgEABIAAACQAAAAAAAAQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAAAAAAAQAAgEAEgDQAEgDAIAAQAIAAAFAFQADAEAAAFIAAARIAGAAIAAAIIgQAAIAAgEQgFAEgHAAQgFABgEgDgAgKASQAAAFAGgBQAEABAFgEIAAgGIgHgBQgIAAAAAGgAAEgRQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgAgOgRQgBgBAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgDAAgCgBg");
	this.shape_36.setTransform(13.4,94.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#245B8F").s().p("AgUAeIAAgJIAGAAIAAgoIgGAAIAAgKIAXAAIAAAKIgGAAIAAAoIAOAAIAAgJIAKAAIAAASg");
	this.shape_37.setTransform(8.6,94.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#245B8F").s().p("AAGAQQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBgBAAIgDgJIgCAJQAAAAgBABQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAgBIAIgGIgKgBQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAAAgBgBQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAIAJAFIgDgJQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAAAABAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAABIgDAJIAIgFQADgCACABQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABABABQAAAAgBABQAAABAAAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAIgKABIAIAGQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgCABIgCgBg");
	this.shape_38.setTransform(4.1,92.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#245B8F").s().p("AgfBMQABgOAGgGQAIgGAQAAQASAAAHAGQAGAGAAAOQAAAZgfAAQgeAAgBgZgAgbAqIgEiOIA/AAIgFCOg");
	this.shape_39.setTransform(250.2,72.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#245B8F").s().p("AATBjIgnhOIgDAAIAABOIg8AAIAAjFIBDAAIAlBQIACAAIAAhQIA9AAIAADFg");
	this.shape_40.setTransform(234.6,72.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#245B8F").s().p("AhBBjIAAjFICDAAIgFA0Ig6AAIAAAYIAzAAIAAAtIgzAAIAAAcIA/AAIgFAwg");
	this.shape_41.setTransform(218,72.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhCAAIAAjFIBUAAQBJAAAABAQgBATgGAMQgGAJgNAJIAdBUgAgPgHIAHAAQAIAAACgEQADgFAAgLQAAgTgMAAIgIAAg");
	this.shape_42.setTransform(201.5,72.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhCAAIAAjFIBUAAQBJAAAABAQgBATgGAMQgGAJgNAJIAdBUgAgPgHIAHAAQAIAAACgEQADgFAAgLQAAgTgMAAIgIAAg");
	this.shape_43.setTransform(183.5,72.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#245B8F").s().p("AhFBjQgVgZAAg0QAAg1AVgZQAVgYAxAAQAwAAAWAYQAUAYAAAzQAAA2gVAZQgWAagwAAQgvABgWgagAgQgQQgFAHAAAaIAAAOQAAAbAFAIQAEAIAOAAQANAAAEgIQADgHAAgbIAAgPQAAgZgEgIQgEgJgOAAQgNAAgDAJgAAEhnQAAgVAXAAQAYAAAAAVQAAATgYABQgXgBAAgTgAgzhnQAAgVAWAAQAYAAAAAVQAAATgYABQgWgBAAgTg");
	this.shape_44.setTransform(164.5,70.5);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#245B8F").s().p("AhVBjIAAjFIBPAAQAyAAAWAaQAUAWAAAvQAABmheAAgAgRAxIAIAAQAPAAAGgMQAEgKAAgaQAAgZgFgKQgFgMgQAAIgHAAg");
	this.shape_45.setTransform(145.4,72.7);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#245B8F").s().p("AhDBeIAEg2QArALAPAAQAJAAAAgHQAAgFgKgFIgTgIQgOgGgIgGQgagRAAgfQAAggATgSQATgSAjAAQAgAAAlAHIgIA4QgogHgMgBQgMAAAAAIQAAADADACIAJAEIATAIQANAFAIAGQAZARAAAdQAABDhKAAQghAAgigIg");
	this.shape_46.setTransform(127.8,72.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#245B8F").s().p("AhVBjIAAjFIBPAAQAyAAAWAaQAUAWAAAvQAABmheAAgAgRAxIAIAAQAPAAAGgMQAEgKAAgaQAAgZgFgKQgFgMgQAAIgHAAg");
	this.shape_47.setTransform(110.8,72.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#245B8F").s().p("AATBjIgnhOIgDAAIAABOIg8AAIAAjFIBDAAIAlBQIACAAIAAhQIA9AAIAADFg");
	this.shape_48.setTransform(91.3,72.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#245B8F").s().p("AAXBjIgHgfIgiAAIgGAfIhBAAIApjFIBhAAIApDFgAAMAbIgMhBIgBAAIgMBBIAZAAg");
	this.shape_49.setTransform(72.6,72.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#245B8F").s().p("AhDBeIAEg2QArALAPAAQAJAAAAgHQAAgFgKgFIgTgIQgOgGgIgGQgagRAAgfQAAggATgSQATgSAjAAQAgAAAlAHIgIA4QgogHgMgBQgMAAAAAIQAAADADACIAJAEIATAIQANAFAIAGQAZARAAAdQAABDhKAAQghAAgigIg");
	this.shape_50.setTransform(55.8,72.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#245B8F").s().p("AAFBjIgThCIgEAAIAABCIhAAAIAAjFIBAAAIAABOIAEAAIAYhOIBJAAIgpBmIAmBfg");
	this.shape_51.setTransform(40.1,72.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#245B8F").s().p("AhABjIAAjFICBAAIgEA0Ig6AAIAAAYIAyAAIAAAtIgyAAIAAAcIA+AAIgEAwg");
	this.shape_52.setTransform(23.6,72.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#245B8F").s().p("Ag9BjIAAjFIBEAAIAACSIA3AAIgFAzg");
	this.shape_53.setTransform(10,72.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#245B8F").s().p("AATBjIgnhOIgDAAIAABOIg8AAIAAjFIBDAAIAlBQIACAAIAAhQIA9AAIAADFg");
	this.shape_54.setTransform(223.2,35.5);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#245B8F").s().p("AAXB0IgGgfIgjAAIgGAfIhBAAIApjGIARAAIgBgHQAAgaAgAAQAeAAAAAYIgBAJIAUAAIApDGgAALAsIgLg6IAAAAIgMA6IAXAAgAgGhaQAAAIAEAAIACAAQAEAAAAgIQAAgIgEAAQgHAAABAIg");
	this.shape_55.setTransform(204.5,33.8);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhBAAIAAjFIBTAAQBIAAAABAQAAATgGAMQgGAJgNAJIAeBUgAgPgHIAIAAQAHAAACgEQADgFAAgLQAAgTgMAAIgIAAg");
	this.shape_56.setTransform(186.9,35.5);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#245B8F").s().p("AhABjIAAjFICBAAIgEA0Ig6AAIAAAcIAsAAIAAAtIgsAAIAABIg");
	this.shape_57.setTransform(171.3,35.5);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhCAAIAAjFIBUAAQBJAAAABAQgBATgGAMQgGAJgNAJIAdBUgAgQgHIAIAAQAIAAACgEQADgFAAgLQAAgTgMAAIgJAAg");
	this.shape_58.setTransform(148.8,35.5);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhCAAIAAjFIBUAAQBJAAAABAQgBATgGAMQgGAJgNAJIAdBUgAgQgHIAIAAQAIAAACgEQADgFAAgLQAAgTgMAAIgJAAg");
	this.shape_59.setTransform(130.8,35.5);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#245B8F").s().p("AhFBjQgVgZAAg1QAAg1AVgXQAWgZAwAAQAwAAAVAZQAVAXAAAzQAAA3gVAZQgWAagwAAQgwgBgVgZgAgQgQQgFAHAAAaIAAAOQAAAbAFAHQAEAJAOAAQANAAAEgIQADgIAAgaIAAgPQAAgZgEgIQgEgJgOAAQgNAAgDAJgAAEhoQAAgTAXgBQAYABAAATQAAAVgYAAQgXAAAAgVgAgzhoQAAgTAWgBQAYABABATQgBAVgYAAQgWAAAAgVg");
	this.shape_60.setTransform(111.7,33.3);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#245B8F").s().p("AhVBjIAAjFIBPAAQAyAAAWAaQAUAWAAAvQAABmheAAgAgRAxIAIAAQAPAAAGgMQAEgKAAgaQAAgZgFgKQgFgMgQAAIgHAAg");
	this.shape_61.setTransform(92.7,35.5);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#245B8F").s().p("AAKBjIgThEIgFAAIAABEIhCAAIAAjFIBUAAQBJAAAABAQgBATgGAMQgGAJgNAJIAdBUgAgPgHIAHAAQAIAAACgEQADgFAAgLQAAgTgMAAIgIAAg");
	this.shape_62.setTransform(74.2,35.5);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#245B8F").s().p("AhABjIAAjFICBAAIgEA0Ig6AAIAAAYIAzAAIAAAtIgzAAIAAAcIA+AAIgEAwg");
	this.shape_63.setTransform(57.9,35.5);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#245B8F").s().p("AgiBjIAAiPIgsAAIACg2ICbAAIgEA2IgqAAIAACPg");
	this.shape_64.setTransform(42.5,35.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#245B8F").s().p("AgiBjIAAiPIgsAAIACg2ICbAAIgEA2IgqAAIAACPg");
	this.shape_65.setTransform(27.3,35.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#245B8F").s().p("AgiBjIAAg/IgziGIBIAAIANBIIACAAIAOhIIBGAAIg1CGIAAA/g");
	this.shape_66.setTransform(11.1,35.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#245B8F").s().p("AATBjIgnhOIgDAAIAABOIg8AAIAAjFIBDAAIAlBQIACAAIAAhQIA9AAIAADFg");
	this.shape_67.setTransform(163.2,-1.7);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#245B8F").s().p("AhABjIAAjFICBAAIgEA0Ig6AAIAAAYIAzAAIAAAtIgzAAIAAAcIA+AAIgEAwg");
	this.shape_68.setTransform(146.6,-1.7);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#245B8F").s().p("AhUABQAAgxAUgZQAVgcAvAAQAlAAAgAKIgLA7QgkgJgPAAQgPAAgGALQgEAJAAAVQAAAbAEALQAFANAPAAIANgCIACgBIAAgTIgQAAIAAgrIBMAAIAABxIgxAAIgFgKIgBAAQgRANgWAAQhKABgBhmg");
	this.shape_69.setTransform(122.9,-1.7);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#245B8F").s().p("AghBjIAAjFIBDAAIAADFg");
	this.shape_70.setTransform(108.9,-1.7);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#245B8F").s().p("AhVBjIAAjFIBPAAQAyAAAWAaQAUAWAAAvQAABmheAAgAgRAxIAIAAQAPAAAGgMQAEgKAAgaQAAgZgFgKQgFgMgQAAIgHAAg");
	this.shape_71.setTransform(94.8,-1.7);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#245B8F").s().p("AAXBjIgHgfIgiAAIgHAfIhAAAIAqjFIBgAAIApDFgAALAbIgLhBIgBAAIgMBBIAYAAg");
	this.shape_72.setTransform(69.9,-1.7);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#245B8F").s().p("AATBjIgnhOIgDAAIAABOIg8AAIAAjFIBDAAIAlBQIACAAIAAhQIA9AAIAADFg");
	this.shape_73.setTransform(51.2,-1.7);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#245B8F").s().p("AATBjIgnhOIgDAAIAABOIg8AAIAAjFIBDAAIAlBQIACAAIAAhQIA9AAIAADFg");
	this.shape_74.setTransform(31.8,-1.7);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#245B8F").s().p("AhTAgIAAiEIBFAAIAAB/QAAASAPAAQAPAAAAgSIAAh/IBFAAIAACDQgBBGhUAAQhTAAAAhFg");
	this.shape_75.setTransform(12.3,-1.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,-20.5,278.5,121.6), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Lager_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FCEA64").ss(1,1,0,4).p("AgUgkIAnAkIgnAl");
	this.shape.setTransform(104,285);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FCEA64").ss(1,1,0,4).p("Ag/AAIB/AA");
	this.shape_1.setTransform(99.5,285);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FCEA65").s().p("AgFAaQAAgGAFAAQAGAAAAAGQAAAHgGAAQgFAAAAgHgAgBANIgDgtIAJAAIgDAtg");
	this.shape_2.setTransform(85.2,284);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FCEA65").s().p("AgRAWIAAgHIAHAAIAAgcIgHAAIAAgHIAPAAIAAAKQAFgLAHAAQAIAAgBAHQABAFgGAAQgDAAgDgDQgFACgDAGIAAATIAIAAIAAAHg");
	this.shape_3.setTransform(82,285.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FCEA65").s().p("AgRAdQgEgDAAgGQAAgGAFgDQAFgEAHAAQAHAAAEACIAAgFQAAgEgCgBQgCgDgGAAIgFABIAAACQAAAFgFAAQgFAAAAgFQAAgDAEgDQAFgEAHAAQAJAAAFAGQADAEAAAEIAAAVIAHAAIAAAHIgPAAIAAgFQgGAGgIAAQgGAAgEgDgAgMAUQAAAFAIAAQAGAAAFgEIAAgHQgFgCgFABQgJgBAAAIgAACgYQAAgHAGAAQAGAAAAAHQAAAFgGAAQgGAAAAgFgAgQgYQAAgHAGAAQAHAAAAAHQAAAFgHAAQgGAAAAgFg");
	this.shape_4.setTransform(77.5,284.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FCEA65").s().p("AAEAkIAAgHIAGAAIAAgUQAAgEgCgCQgCgCgDAAQgHAAgFAGIAAAWIAGAAIAAAHIgVAAIAAgHIAGAAIAAg5IgGAAIAAgHIAPAAIAAAkQAHgHAHAAQAHAAADAEQADADABAGIAAAWIAGAAIAAAHg");
	this.shape_5.setTransform(72.3,283.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FCEA65").s().p("AgKAkIAAgHIAHAAIAAg5IgHAAIAAgHIAOAAIAABAIAHAAIAAAHg");
	this.shape_6.setTransform(65.9,283.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FCEA65").s().p("AgKAkIAAgHIAHAAIAAg5IgHAAIAAgHIAOAAIAABAIAHAAIAAAHg");
	this.shape_7.setTransform(63.1,283.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FCEA65").s().p("AgVAUQABgGAEgDQAFgEAHAAQAGAAAFACIAAgFQAAgDgCgCQgDgDgFAAIgFABIAAACQAAAFgFAAQgFAAAAgFQAAgDAEgDQAFgEAHAAQAKAAAEAGQADADAAAFIAAAVIAGAAIAAAHIgOAAIAAgFQgGAGgHAAQgOAAgBgMgAgMAUQAAAFAIAAQAFAAAGgEIAAgHQgEgCgGABQgJgBAAAIgAACgYQAAgHAGAAQAGAAAAAHQAAAFgGAAQgGAAAAgFgAgQgYQAAgHAGAAQAHAAgBAHQAAAFgGAAQgGAAAAgFg");
	this.shape_8.setTransform(59.4,284.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FCEA65").s().p("AgFAXIgBgGIAAgYIgIAAIAAgHIAIAAIAAgKIAHgDIAAANIAOAAIAAAHIgOAAIAAAWIABAEQAAACAFAAQAEAAAEgDIgBAIQgEACgFAAQgHAAgDgFg");
	this.shape_9.setTransform(55,284.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FCEA65").s().p("AgPARQgCgCAAgEQAAgFAFAAQAFAAAAAFIgBACQAEACAEAAQAJAAAAgFQAAgEgJgCQgIgDgDgBQgFgDAAgFQAAgFAFgEQAEgEAHAAQAJAAAFAEQACADAAACQAAAFgEAAQgGAAAAgEIABgCQgCgCgFAAQgHAAAAAGQAAAEAJACQAQADAAAJQAAAGgGAEQgFADgHAAQgJAAgGgFg");
	this.shape_10.setTransform(51.2,285.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FCEA65").s().p("AgNAQQgGgGgBgJQABgJAFgGQAGgHAIAAQAKAAAFAGQAFAGABAIIgBAEIgfAAQADAMAMAAQAGAAAIgEIAAAHQgGAEgJAAQgKAAgGgGgAgLgDIAXAAQgBgLgLAAQgJAAgCALg");
	this.shape_11.setTransform(46.6,285.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FCEA65").s().p("AgYAgIAAgIIAIAAIAAgvIgIAAIAAgIIAZAAQAWAAAAAQQAAAMgLADQANADAAALQAAAJgGAEQgGAGgLgBgAgIAYIAKAAQAOAAAAgKQAAgLgPAAIgJAAgAgIgDIAIAAQAOAAAAgLQAAgKgOAAIgIAAg");
	this.shape_12.setTransform(41.1,284);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#23598F").s().p("AnUCJIAAkRIOpAAIAAERg");
	this.shape_13.setTransform(73.1,284.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(26.2,270.6,93.9,27.4), null);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Lager_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AriNhIAA7BIXEAAIAAbBg");
	mask.setTransform(73.9,86.5);

	// Lager_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#245B90").s().p("AgZLbQiVgFiFg+QiCg8hhhpQhihogziGQg1iJAGiUQAFiVA+iGQA8iBBphiQBphiCFgzQCKg0CTAFQCVAFCGA+QCBA8BiBpQBiBpAzCFQA0CKgFCUQgFCVg+CFQg8CChpBhQhpBiiFAzQh9AwiGAAIgbgBg");
	this.shape.setTransform(74.5,73.2);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(1.4,0,146.4,146.4), null);


(lib.Textsymbol = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Lager_1
	this.instance = new lib.Symbol4();
	this.instance.parent = this;
	this.instance.setTransform(141,61.6,1,1,0,0,0,141,61.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Textsymbol, new cjs.Rectangle(0,0,282,122.3), null);


// stage content:
(lib._320x320 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* Klicka för att Gå till webbsida
		Om du klickar på den angivna symbolinstansen laddas webbadressen i ett nytt webbläsarfönster.
		
		Instruktioner:
		1. Ersätt http://www.adobe.com med önskad webbadress.
		      Behåll citattecknen ("").
		*/
		
		this.movieClip_1.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
			window.open("https://www.garageportexperten.se/trygghet/", "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(390));

	// Lager 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#296093").s().p("AlOLBIgGgcQgEgQAAgKIAA0mIABgNQAXgYAnAAQELABEKgBQAoAAAWAYIAABcIgXAXInjAAIAAHXIEwAAQAlgBAJAHQAJAJgCAkIAAA+IgaAaIlLAAIAAIRIH+AAIAbAaIAABQIgZAZg");
	this.shape.setTransform(251.9,265,0.076,0.076);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#285F92").s().p("AkxLBIhHAAQgYgbAAgmIAB0NQABgXAOgNQAOgOAYgBIE6AAQBJgBBXAXQAvAMBCApQAtAdAkAzQAVAeAiBEQADAFAAASQAAAPAKAHQgBASAIAyQAHAqgFAaQgDANgEAkQgDAfgGASQgUA/gNAXQgeA5g1ArQgrAkhEAhQgTABgrAMQgoAKgYAAQg1gCi+ABQgYAAgGAGQgGAHAAAYQgBFUABCqQAAAngJAIQgHAGgfAAIgJAAgAhlo2IhzACQgVAAgGAHQgGAGAAAWIAAHWQAAAWAGAGQAGAHAVAAIC+AAQA3ABA8gWQB4gqAVhnQAKgHAAgPIAAgYQAQg7gFgpQgEgbgWg6QgxiBikgNQgogDg5AAIgQAAg");
	this.shape_1.setTransform(259.4,265,0.076,0.076);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#285F92").s().p("AgDLjQhOgJgVgEQg4gLgogWQhcgygthIQgcgsgPg6IgShYQgJgvAAhHQAChOgBgoQgBgwAAhIIAAlnQAAgLAHgYQAGgWgBgOQgEgjANgeIAag5QAPggAPgXQAvhHBNgnQBCgiA2gFQBPgIAfAAQAkAABIANQBNANAcAPQAzAbARAiQAVArgaA/QgaAGgbgKIgtgVQhCgcg9gNQgagGgkABIg+AEQgiADggARQhCAjgaAvQgfA7gLBAQgGAngBBNQgCFfACDfQABBcAmBIQAqBRBoAdQAwAOA0gGQBYgKA0gyQA+g7ANhRQAIgvAAgOIABk+IibAAQgPABgHAAQgMgBgHgKQgeAFgEgmQgCgeABgOQACgYANgSIFNAAQATAAAHAHQAGAGAAATIACDiQABCGgEBdQgHCOhpBwQgaAdg+AgQg4AdgoAJQgwALgmAAIgYgBg");
	this.shape_2.setTransform(243.8,265,0.076,0.076);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#265D91").s().p("AFPLBQgWgIgHgXQgFgcgFgMQgGgOgGgiQgFgggHgPQgEgLgHgiQgFgdgLgPQAAgbgLglQgOgqgFgVQgFgUgGgEQgEgDgVAAIl4gBQgUAMgHAZIgIAoQgJAwgZBeQgEATgQA6QgOAvgFAeQgBAIgHAKIgOATIhoAAQgqgBAJgnIAPgyIAPgxIAeh1IBQkyIAXhUQAOgzAHggQAGgaASg9QAQg4AGggQAFgZALgkIASg9IAYheIAUhDQALgpAEgcQADgVAJgdIAPgwQAKghAOgLQAPgLAgABQA/gBAfABQAaAAAOAMQANALALAcQAPAlANA3IAWBcIARA9QALAnAFAVQAKAwAbBcIBoGRIAYBbQAPA2AIAkQASBJAaBYQAHAXAKArIARBBQAMAmguAAgAhZiwQg5DageB5IFhAAIixqsIhZFZg");
	this.shape_3.setTransform(218.9,265,0.076,0.076);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#265D91").s().p("AFFLAQgRgZgKgpQgKgvgHgXIgRhEQgLgpgJgaQgHgUgGgeIgKgyQgIglgjAAIlhAAQgQAAgMAJQgMAJgDANIg9D1QgNA3gRAvQgDAHgHAJIgLAOIh+AAQgLgsATguQAIgTAIghIANgzQARg2AShSQAGgcARg8QARg5AGgfQAFgYAMgmIASg/IAYhZQAIgaAJgqIAQhEQAih3AOg9QAGgaASg4QAQg2AGgdQAEgWAOguQAMgtAEgYQAGgkAVgSQAUgQAmAAIBZAAQAyABAOAsQAIAbANA3QAYBjAMAkQAPAsATBcIAiCCIAZBfIAZBZQAPA2AHAkQAMA8AiB1QARBFAcBgQAWBKAVBnIAIArQADAYgEATgAgLnMQgEATgFANQgGAOgDAMIgPBFQgJAngJAcQgMAjgNA0IgVBYIgYBTQgOAxgHAiQgCAPgKAdQgHAaAGATIFPAAIABgXQAAgOgCgIQgCgLgNgjQgJgdgDgSQgEghgQg3QgThAgEgYQgHgkgPg2IgZhaQgbhpgOg1QgBgCgFgCIgJgDIgGAjg");
	this.shape_4.setTransform(235.4,265,0.076,0.076);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#275E91").s().p("AhSLaQhVgQgigTQg+glgtg0Qgyg6gVhEQgVhIAAg8QABg7AAkiIAAlZQgCh7A9hdQAYglAIgLQAUgZAXgQQA3gkAdgPQAlgUA5gHIAcgFIAcgEQAlgDAWADQA6AHAeAHQAwALAkATQBGAnAqAyQArA0AYBNQAVBCAAA4IAALKQABAbgNA0QgMA0gOAhQgrBmhrA/QhLAshDgDQgIAAgNAEIgUAFQgHACgMAAQgfAAg9gLgAiLo1Qg6AigfBJQgRAmgHAxQgEAigCA4QgECSAECtQABA2gDBqQAABgAKBBQALBLARAmQAUAsAhAcQAoAgA9AQQATAFAdABIAvADQAUACAagJIAsgSQAsgOAZgiQBDhegCheQgChGAAhmIABisIAAliQAAgogKgfQgVhEgrgqQgtgthBgMQgigGggAAQhNAAg+Alg");
	this.shape_5.setTransform(267.6,265,0.076,0.076);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#285F92").s().p("AEaLAQgUgBgMgeIgehGQgTgrgKgcQgFgOgNgcQgNgcgFgPQgMglgUgvIgkhTQgohngagxQgHgNgIgFQgHgFgOAAIj0AAIAAIaQAAAMgDATIgGAfIhsAAQgTAAgGgHQgHgGgBgSIAA1JIAZgZIEiAAIA3AAIAaAAQAPAAALAGQAIAEARgBQAUAAAIACQBCARAlARQA3AYAmAkQBMBKAZBaIAKAiQAGATAAAPIAEBGQABAogFAdQgPBXghA5QgqBJhRAuIgzAkQAvBjA0CAQAcBHA8COQAhBTAZA6QAHAPABAMQABAMgHAHQgGAGgLABIg3AAQgeAAgUgBgAh5o1IiJABIAAISIDVAAQA6ACA/gWQBEgYAfglQAzg+ADhBQADg5gBgSQAAgqgKghQgQg0gagkQgXgdg1gcQgvgYgqgBQgvgDhCAAIgWAAg");
	this.shape_6.setTransform(227.4,265,0.076,0.076);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#285F92").s().p("AD/KvIgTgqQgMgYgFgSQgJgdgSgrIgdhGQgMghgYg3IglhXQgOglgYg1IgohbIkTAAIgBI6QAAARgHAHQgGAGgTAAQgmABglgBQgTAAgLgMQgMgLAAgTIAAgZQAAvWgBkZQAAgsAOgRQARgUAuACQCFAECEgEQA+gDBSAPQC7AiBNCZQAjBGAHBEIAFApQAEAYgCAQQgIBDgFAaQgKA0gVAlQg7BqhmA1IgZAMIAbA2QAQAfAGAWQAFARAPAeQAOAfAFAQQANAnAXA2IAoBaIAhBSQAUAxAQAfIAMAbIANAbQAFAKgJALQgJALABAGIhzABIgBAAQgVAAgJgTgAhxo1IhxACQgaAAgGAGQgFAGAAAcIAAHHQAAAVAGAHQAHAGAVAAIDCABQAuAABGgVQBMgXAqhLQAohJgEhrQAAgGgEgLQgFgMAAgGQAAgOgGgQIgMgcQgzh7iegOQglgEgxAAIgaABg");
	this.shape_7.setTransform(276.3,265,0.076,0.076);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#245B90").s().p("EggFAIHQgSgBgHgGQgFgHgBgTIAAvhIACgLMBBHAAAIAAPYIAAAeQgEAXgWAAg");
	this.shape_8.setTransform(247,247.9,0.076,0.076);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#245B90").s().p("EggjAIIIAAvYIgBgSQAAgKACgHQACgFAGgGQAGgFAFgCQAIgCAMABIAUAAMBAMAAAIAAQOg");
	this.shape_9.setTransform(247,238.2,0.076,0.076);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#5081A9").s().p("AgTNwIAA7fIAKAAIgBawQACAFARAQQANAMgCAOg");
	this.shape_10.setTransform(207.7,280.1,0.076,0.076);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#275E91").s().p("AALLBQgjABgTgBQgZgBgBgaIAAykQAAgogIgHQgIgIgnABIj7AAIgYgaIAAhaIAbgYIAQAAIK2gBQAjAAAbAVIAABkQgbAVgjAAQg9gCipABQgaAAgGAHQgGAGAAAbIAASQQAAAugGAHQgHAJgiAAIgMgBg");
	this.shape_11.setTransform(283.3,265,0.076,0.076);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#285F92").s().p("AgFLkQhXgKgNgDQg4gKgogWQg+gjgtg1Qgyg6gVhFIgGgbIgGgcIgDgCIgFgCIAAtRQAKgDABgPQACgQAHgEQAKgpAOgdQAOgdAZgeIASgaQAMgPAJgHQA/gwA2gUQASgHAagHQAcgIBAgFQBEgFAXAHQALADASACIAcAEIAcAFIAbAGQA4ANA4AqQAGAFAFAHQAGAIAAAHQAEAqgDAwQAAAEgGAGQgGAFgEABQgZACgSgHIgigOIgigPQgvgSgigIQgsgLgoACIgvABQgcABgUAGQh6AjgnCAQgLAkAAAeQACGfgBEqQgBBGAtBNQAlA/BUAcQA6AUBJgNQBNgNAsgmQA0gtAUhLQAHgaADgYIAAgyIAAkwQgPgCgYAAIgnABQgygBgZABQgWABgOgFQgSgGgNgQIAAhHQABgUAGgGQAHgGAWAAIEsAAQAVAAAGAGQAHAHAAAVIAAHGQABAggLAmIgXBCQgSA1gvAtQgnAmgQANQggAaggAMIgVAJQgNAGgJACQgLADg2AHIgpAIQgQACgMAAIgLgBg");
	this.shape_12.setTransform(210.6,265,0.076,0.076);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#245B90").s().p("AhjOJIgcgWQgXgWAAgdIAA12IgBgiQgDgTgSgPIkIAAQgsAAgNgFQgNgGghggIAAi9IAGgCQAFgDAEgDQAcgeAsAAIOHAAIAKAAQAjABAVAWQAVAVABAjQABA5gBA6QgBAhgWAWQgVAVgjAAIkJAAQgiABgGAGQgGAGABAjIAAVsQAAAugIAPQgHAQgkAag");
	this.shape_13.setTransform(261.7,279.9,0.076,0.076);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#245B90").s().p("Am8OJQADgOgOgMQgRgQgCgFIAA6wQARgxA6gBIMBAAQAWAAATAOQAHAFAaAZIAAC3IgOANQgcAfgtgBIntAAIghAAQgLANgDARQgBAKAAAVQABCrgBCpQAAAnAQAUIFgABQAvAAAeAeQAUAUADApQAFAxgFAiQgEAggQAjQgJAXgmAEIliABQgYAAgMALQgLALAAAZIAAG8QABAJADAPIAHAYIIkAAQAQgBARAGQAKADAUAJQAVAJAIAPQAIAOAAAWIAABuQAAA6guARIgEAIg");
	this.shape_14.setTransform(211.2,279.9,0.076,0.076);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#255C90").s().p("AmsOJIgWgRQgMgLgFgJQgMgcABgqIAA46IgCgaQAAgQALgJQgBgdAWgMQANgHAfgIQAHgBAKAAIASABILJgBQAkgBAYALQAcALATAbIAACyIgSASQgaAcgqgBIoGAAIgZAZIgBF3QABAVACALQADAPALAMIFlABQApAAAaAaQAbAZABAoIACAvQAAAcgCATQgFAlgRAWQgYAcgpgCQhFgDhgABIikABQgeAAgLALQgLALAAAeIAAGyQAAAKAEAQIAFAbIImABQAZAAAOAEQAjALANARQAMARAAAmIABBkQAAA5gvARIgDAIg");
	this.shape_15.setTransform(242.4,279.9,0.076,0.076);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#255C90").s().p("AmtOJIgWgSQgMgKgFgKQgMgbABgrIAA45QAAgdAGgSQASg8BGAAILxgBQAwAAAdAqQAHAKADASIAEAfQADAYgCAkQgBAPgJAoQgDARgXASQgWASgTABIgeAAInfAAQgSAAgLAGQgNAGgLAQIAAE1IAABBQgCAgARAaIFnABQAqAAAaAaQAbAbAAArIABAtQAAAagCASQgCAfgJARQgMAWgaAIQgRAFgVAAIlkAAQgZAYAAAnIAAGpQABAKADAPIAGAbIIlABQAZAAAOAEQAjAKANASQANARAAAlIAACLIgyAsg");
	this.shape_16.setTransform(271.3,279.9,0.076,0.076);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#245B90").s().p("AnzOJIgcgWQgXgWABgdIAA5mQAAggAGgQQARgyA4AAID4AAQCUgBBiADQAqABA0ANQAgAJA8AUQCFAuBjB2QBABNAZBvQADAKACAaQABAWAEAMQAJAaAAAuQABBdgoBzQggBcgzAxQgRAQghAiQgeAegaAOQg4AfgiAPQgzAXguAKQg6ANgdAEQgTADgdAAIgugCIiWABQgfAAgLALQgLALAAAdIAAJ7IgyArgAj1pgQgDAOgBAJIAAHGQAAAaAHAFQAGAGAcAAQBhABBhgBQBwgBBLhMQAkgkAVgtIAUh1IgEgNIgDgOQgDgIAAgGQABg0gdguQgWgjgvgoQgMgJgYgLQgegMgIgFQgHgEgUAAQgTABgJgJQgFgFgOABIgYACIjRAAIgHAag");
	this.shape_17.setTransform(232.4,279.9,0.076,0.076);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#255C90").s().p("AGROJQgCgLgOABQgQAAgEgIQgEgIgMgKQgNgMgEgGQgYgggRgfIgdg6QgSgjgPgVQgOgTgUgnQgWgqgLgRQgXgjgeg3IgxhcIgqhNQgDgEgGgEIgJgIQgNALgKAWIgQAhQgdArgqBLQgyBagSAdQgWAlgmBDIg8BpQglA/gOAPQgIAIgpAZIjwAAIgIgLQgWgYgCgMQgCgMAQgcIB9jaIBjiuIArhNQAagtAVgfQAJgPANgXIAVgnIA5hmQAig7AZgoQAPgZgRgZQgNgTgUgmQgVgngLgRQgTgfgmhEQgkhCgWghQgKgPgNgZIgVgqQhFh9ggg0Ig0heQggg5gYgjQgcgoAlglIAPgQIBeABQA5ABAmgCQBMgFAyBJQAOAVAXArQAYAuAMATQASAcAnBHQAjBAAXAiQAMASAQAhIAaA0QAMAWAfAtIAQgeQASgcAohHQAjhAAXgiQALgRARgiQARgkAJgPIBaieQAng/AygJQAZgEAIAAIClAAQAVAAAIADQAIADAZASIgBAQQAAALABAGQABAMgEAMIgNAUQgLAPgMAZIgWApQggA8hEB3QhgCpgYApIg+BrQglBAgcApQgGAJgMAbQgLAWgKAMQgDADABAJQAAAIADAGIBOCJIASAgQBFCBAvBJQAQAaAcA4QBFB9AgA1QALARApBNQAfA6AZAhQADADADAIIAFAKQAHAKACARIABAdQACAOgOAHQgQAKgCAFg");
	this.shape_18.setTransform(221.4,279.9,0.076,0.076);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#255C90").s().p("AFCOKQg1glgOgsQgHgfgHgNQgQgegQgqIgchJQgchJgZg3QgNgdgQgpIgchHQgQgpg2h4QgGgQgLgDQgggKgYgBIizAAQgiAXAHAjIABAeIAAJXIgyArIjIAAIgcgXQgXgVAAgdIAB5dIgCgaQAAgQAKgJQAAgdAWgMQANgHAfgIQAFgCAJABIAPABIGpAAQBkAACCAtQBuAlBNBPQAmAnAQATQAbAiAPAhQAQAiAMArQAIAZANA2QAHAcABAlIAABCQgBA6gbBaQgUBCgqBEQgWAigxApQguAogpAWQgCAKACAMIAIAWQAMAkAjBNQAhBIAMAqQAFAPALAXIASAmIAnBZQAZA5ANAgIAsBrQAeBEAPAmQAJAXgDAPQgDAPgRAOQgCACgFAKgAkSpbQgDARAAALIgBGyQAAAgAHAIQAJAJAjgBQA9gBB8ABQAPAAAygIQAigFAigVQATgLAngfQAdgXAVg3QAIgWAGgeIAIg1QACgOgEgTIgGghQgJg5gYgmQgZgmgwgiQgPgKgWgKIgmgQQgRgIgZgCIgvgCIjUAAIgFAeg");
	this.shape_19.setTransform(252.6,279.9,0.076,0.076);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#265D91").s().p("AFFOJIgggkQgOgTgHgNIgthWQgcg2gTggQgQgagag1Qgcg3gPgaQgZgqgfhAIg1hrIgdg9QgSglgPgWQgPgXgQgfIgcg4QgKgWgTgiIgeg2IhUicIgGADIAAQJQAAAdgXAWIgbAWIjIAAIgcgWQgXgWAAgdIAA5cQAAgpASggQATghAhgBQA+gCBiACQAnAAAVAnIBGB+QAvBUANAaQApBSASAdQARAaAVArIAiBHIAwBiQAdA5AWAmQAOAYAbA3QAZAzAQAaQAVAhAhBCQAjBGASAfIAcAwIAAw4IAegaQAagSAVAAQAvABBdAAQAcAAAUASQATASAKAdQAIAcAAA2QABMDgBMEIACAdQgBARgKAKQABAVgMAQQgIAKgVAPg");
	this.shape_20.setTransform(281.5,279.9,0.076,0.076);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#245B90").s().p("EggcAIHIAFg0QAEgdAFgUQAGgSAFgZIAJgsIAIg2QAFgfAJgUQAFgKACgZQABgWAIgMQAHgKACgSIABggQABgIAIgZQAGgTgEgOQAIgHACgVQABgUAJgIQgBgaAIglQAMgqADgVIAJg3QAFggALgWQADgHAAgYQAAgTAKgKQABgeAPg4QAPg5ABgdQAAgDAEgJQAFgIAAgGMA6QAAAQAHAtAZBmQAGAbAIA2QAKAwAPAeQgBAZAIAkIANA8IAKA6QAHAgAJAXQADAHAAAYQABATAJAKQAFAnAMA4IAVBeIAOA+QAIAlAAAbQABAVALAYQAHAQAAAXQABAhABAFg");
	this.shape_21.setTransform(246.9,228.6,0.076,0.076);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(390));

	// logga
	this.instance = new lib.Leksandsdorren_symbol_cmykepsResurser();
	this.instance.parent = this;
	this.instance.setTransform(12,9,0.21,0.21);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(390));

	// rund
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FCEA63").s().p("AgIAuQgPgDgHgLQgJgNAFgUQAEgYAPgMQANgLAQADQAPADAFAIQADAFgBAGQAAAEgEACQgDADgEgBQgFgBgCgDQgCgDAAgEIABgEIgHgDQgIgBgHAHQgKAHgDAPQAJgJAOADQAOADAHAJQAIAKgDAMQgCANgMAGQgIAFgJAAIgIgBgAgMADQgHADgBAHQgCAHAFAGQAEAGAIABQAHACAGgEQAGgEABgHQACgHgEgFQgEgGgIgBIgEgBQgFAAgEADg");
	this.shape_22.setTransform(270.1,102.9,0.768,0.768);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FCEA63").s().p("AgvA3IBTh2IAMAIIhTB3g");
	this.shape_23.setTransform(264.5,102.4,0.768,0.768);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FCEA63").s().p("AgJAwQgQgDgHgKQgEgEABgHQABgEAEgDQADgCAEAAQAEABACAEQADADgBAEQAAAAgBABQAAAAAAABQAAAAgBABQAAAAAAABQAFADAFAAQAIACAFgEQAGgEABgIQAEgPgSgEQgKgBgIACIgHgFIAPgtIAvAKIgDAOIgjgHIgHATIAMABQAOADAHAIQAIAKgDANQgCAOgLAHQgIAFgIAAIgJgBg");
	this.shape_24.setTransform(259,101.9,0.768,0.768);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FCEA63").s().p("AgZAeIADgNIARADIAIgtIgPABIAAgNIAagBIAHABIgMA9IARADIgCANg");
	this.shape_25.setTransform(253.6,100.6,0.768,0.768);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FCEA63").s().p("AAWAkIACgOIAJADIAFgaIAAgGQgBgFgGgBQgGgBgKAFIgGAdIAIABIgCANIgfgGIACgNIAJACIAFgZQAAgEAAgDQgBgEgGgBQgGgCgKAFIgGAdIAIACIgCANIghgHIACgMIAJABIAIgjIgKgCIADgNIAYAFIgCAKQALgKALACQAKACAEAIIABAEQAMgIALACQANADADAJQABAGgBAHIgGAcIAJACIgCANg");
	this.shape_26.setTransform(244.2,99,0.768,0.768);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FCEA63").s().p("AgBAMQgFgBgDgEQgCgEABgEQABgFADgDQAFgCADAAQAFABADAEQACAFgBADQAAAFgEADQgDACgEAAIgBAAg");
	this.shape_27.setTransform(238,99.4,0.768,0.768);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FCEA63").s().p("AgFAgQgPgDgIgLQgHgLADgNQACgNALgHQALgIAOADQAPADAIALQAHALgDAMQgCANgLAIQgJAGgKAAIgGgBgAgJgPQgFAEgCAIQgCAIAEAGQAEAHAHABQAHACAGgFQAFgEACgJQACgHgEgHQgEgGgHgCIgDAAQgFAAgFAEg");
	this.shape_28.setTransform(234.1,97,0.768,0.768);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FCEA63").s().p("AgBAMQgFgBgDgEQgCgEAAgEQABgFAEgDQAEgCAEAAQAFABADAEQADAEgBAEQgBAFgEADQgDACgEAAIgBAAg");
	this.shape_29.setTransform(229.6,97.7,0.768,0.768);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FCEA63").s().p("AgCAqQgNgDgCgJQgBgEAAgGIAHgfIgNgDIAEgNIALADIADgNIAPgEIgDAUIATADIgDANIgTgDIgEAcIAAAFQABADAEABQAEABAIgCIgDANQgFABgFAAIgFAAg");
	this.shape_30.setTransform(226.5,94.8,0.768,0.768);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FCEB4F").s().p("AgBANIgJAGIgLgJIAJgJIgKgEIAGgNIALAFIADgLIAPADIgCAMIALgBIACANIgLABIAFAMIgNAFg");
	this.shape_31.setTransform(295.9,78.8);

	this.text = new cjs.Text(" ", "bold 3px 'Passion One'", "#FCEB4F");
	this.text.lineHeight = 4;
	this.text.parent = this;
	this.text.setTransform(290.3,91.5,0.768,0.768,11);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FCEA63").s().p("AhGBkIAeiVIgugJIANg3IChAfIgQA4IgrgJIgdCVg");
	this.shape_32.setTransform(286.6,84.1,0.768,0.768);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FCEA63").s().p("AhGBkIAdiUIgugJIAOg4IChAfIgPA4IgsgJIgdCVg");
	this.shape_33.setTransform(274,81.6,0.768,0.768);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FCEA63").s().p("AAYBnIgBghIgjgHIgOAfIhDgNIBTjFIBkAUIAEDVgAAAAVIAaAGIABhHIgBAAg");
	this.shape_34.setTransform(258.7,79.8,0.768,0.768);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FCEA63").s().p("AgDBuIhegSIAojMIBcARQAlAIAPAQQAPARgFAcQgGAagaAKIAAACQAZASgHAjQgKAwgyAAQgMAAgOgDgAgSBBIAJACQAJACADgEQAEgDACgMQADgMgDgGQgCgGgHgCIgKgCgAgDgNIAJACQAMADADgSQAEgTgMgCIgKgCg");
	this.shape_35.setTransform(245.9,76.4,0.768,0.768);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FCEA63").s().p("AAYBnIgBghIgkgHIgNAfIhCgNIBSjFIBkAUIADDVgAAAAVIAbAGIAAhHIgBAAg");
	this.shape_36.setTransform(230.4,74.3,0.768,0.768);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FCEA63").s().p("AgBBpIgHhLIgFgBIgOBHIhEgNIAojNIBXARQAmAHAPAUQAQAUgHAiQgEAUgJAKQgIAKgQAGIAOBdgAgHgLIAIACQAHABAEgDQAEgEADgMQADgTgNgDIgJgCg");
	this.shape_37.setTransform(217.1,71.3,0.768,0.768);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FCEA63").s().p("ABsDCQg1gKgOgiQgMgdALg9QAMg8AWgWQAagbA1AKQA3ALAOAiQAMAcgMA+QgMA9gWAWQgSASghAAQgNAAgQgDgAB8AgQgEAJgGAeIgBAHQgHAjABAKQAAAPANACQAMADAGgOQAEgKAGgiIACgHQAGgegBgKQgBgOgMgDIgEAAQgJAAgFALgAh4CQIClkuIBNAPIimEugAiZAoQg1gLgOghQgMgdALg8QAMg9AWgXQAbgbA1ALQA2AKAOAjQAMAdgMA9QgMA8gWAWQgTATghAAQgNAAgPgDgAiJh5QgEAIgGAeIgBAHQgHAiABALQAAAPANADQAMACAGgOQAEgJAGgjIACgHQAGgegBgJQgBgPgMgCIgEgBQgJAAgFAMg");
	this.shape_38.setTransform(278.8,55.8,0.768,0.768);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FCEA63").s().p("AggCnQhLgPgVgxQgSgpARhVQARhXAgggQAlgnBLAPQBNAPAVAyQARApgRBWQgRBXgfAfQgbAbgvAAQgSAAgWgEgAgJhAQgFAMgJAsIgCAJQgJAxAAAOQABAWATAEQAPADAIgUQAGgNAKgxIACgKQAIgqgBgOQgBgUgSgEIgFAAQgMAAgHAPg");
	this.shape_39.setTransform(249.8,50.2,0.768,0.768);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FCEA63").s().p("AiFCHIAFg5QBNgyARgOQAqghAGgcQAFgZgYgFQgYgEg6AEIABheQBBgMA6ALQA4ALAZAhQAXAfgJAvQgJArgaAeQgUAYgxAiIgBACIBNAPIgQBQg");
	this.shape_40.setTransform(229.4,46.7,0.768,0.768);

	this.instance_1 = new lib.ClipGroup();
	this.instance_1.parent = this;
	this.instance_1.setTransform(256.2,75.7,0.768,0.768,0,0,0,74,86.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.text},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22}]}).wait(390));

	// TEXT3
	this.instance_2 = new lib.Textsymbol();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-137.2,157.1,1,1,0,0,0,141,61.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({regX:134.5,regY:64.5,x:-143.7,y:160.5},0).wait(129).to({x:-122},0).wait(1).to({x:-100.2},0).wait(1).to({x:-78.5},0).wait(1).to({x:-56.7},0).wait(1).to({x:-35},0).wait(1).to({x:-13.2},0).wait(1).to({x:8.5},0).wait(1).to({x:30.2},0).wait(1).to({x:52},0).wait(1).to({x:73.7},0).wait(1).to({x:95.5},0).wait(1).to({x:117.2},0).wait(1).to({x:138.9},0).wait(1).to({x:160.7},0).wait(115).to({x:136},0).wait(1).to({x:111.4},0).wait(1).to({x:86.8},0).wait(1).to({x:62.1},0).wait(1).to({x:37.5},0).wait(1).to({x:12.9},0).wait(1).to({x:-11.7},0).wait(1).to({x:-36.4},0).wait(1).to({x:-61},0).wait(1).to({x:-85.7},0).wait(1).to({x:-110.3},0).wait(1).to({x:-135},0).wait(1).to({x:-159.6},0).wait(120));

	// text 2
	this.instance_3 = new lib.Symbol2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-154.6,219.9,1,1,0,0,0,139.5,91);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(132).to({_off:false},0).wait(1).to({regX:127.8,regY:43.6,x:-166.3,y:172.5},0).wait(139).to({x:-141.7},0).wait(1).to({x:-117.2},0).wait(1).to({x:-92.6},0).wait(1).to({x:-68},0).wait(1).to({x:-43.4},0).wait(1).to({x:-18.9},0).wait(1).to({x:5.7},0).wait(1).to({x:30.3},0).wait(1).to({x:54.8},0).wait(1).to({x:79.4},0).wait(1).to({x:104},0).wait(1).to({x:128.5},0).wait(1).to({x:153.1},0).wait(77).to({x:129.4},0).wait(1).to({x:105.8},0).wait(1).to({x:82.1},0).wait(1).to({x:58.4},0).wait(1).to({x:34.7},0).wait(1).to({x:11},0).wait(1).to({x:-12.6},0).wait(1).to({x:-36.4},0).wait(1).to({x:-60},0).wait(1).to({x:-83.7},0).wait(1).to({x:-107.4},0).wait(1).to({x:-131.1},0).wait(1).to({x:-154.8},0).wait(17));

	// text 1
	this.instance_4 = new lib.Symbol3();
	this.instance_4.parent = this;
	this.instance_4.setTransform(116.1,144.2,1,1,0,0,0,89.9,42.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(118).to({x:96.9},0).wait(1).to({x:77.8},0).wait(1).to({x:58.7},0).wait(1).to({x:39.5},0).wait(1).to({x:20.3},0).wait(1).to({x:1.2},0).wait(1).to({x:-18},0).wait(1).to({x:-37.2},0).wait(1).to({x:-56.3},0).wait(1).to({x:-75.5},0).wait(1).to({x:-94.6},0).wait(1).to({x:-113.8},0).wait(246).to({x:-96.1},0).wait(1).to({x:-78.4},0).wait(1).to({x:-60.7},0).wait(1).to({x:-43},0).wait(1).to({x:-25.4},0).wait(1).to({x:-7.7},0).wait(1).to({x:10},0).wait(1).to({x:27.7},0).wait(1).to({x:45.4},0).wait(1).to({x:63.1},0).wait(1).to({x:80.8},0).wait(1).to({x:98.4},0).wait(1).to({x:116.1},0).wait(3));

	// knapp
	this.movieClip_1 = new lib.Symbol1();
	this.movieClip_1.name = "movieClip_1";
	this.movieClip_1.parent = this;
	this.movieClip_1.setTransform(250,439,1,1,0,0,0,250,500);

	this.timeline.addTween(cjs.Tween.get(this.movieClip_1).wait(1).to({regX:73.1,regY:284.3,x:73.1,y:223.3},0).wait(117).to({x:54},0).wait(1).to({x:34.8},0).wait(1).to({x:15.7},0).wait(1).to({x:-3.5},0).wait(1).to({x:-22.7},0).wait(1).to({x:-41.8},0).wait(1).to({x:-61},0).wait(1).to({x:-80.2},0).wait(1).to({x:-99.3},0).wait(1).to({x:-118.5},0).wait(1).to({x:-137.6},0).wait(1).to({x:-156.8},0).wait(246).to({x:-139.1},0).wait(1).to({x:-121.4},0).wait(1).to({x:-103.7},0).wait(1).to({x:-86},0).wait(1).to({x:-68.4},0).wait(1).to({x:-50.7},0).wait(1).to({x:-33},0).wait(1).to({x:-15.3},0).wait(1).to({x:2.4},0).wait(1).to({x:20.1},0).wait(1).to({x:37.8},0).wait(1).to({x:55.5},0).wait(1).to({x:73.1},0).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-118.2,169,591,277.8);
// library properties:
lib.properties = {
	id: '20BEF08A988D4CF8A646CE8DED4FAA37',
	width: 320,
	height: 320,
	fps: 24,
	color: "#FFEB41",
	opacity: 1.00,
	manifest: [
		{src:"images/Leksandsdorren_symbol_cmykepsResurser.png", id:"Leksandsdorren_symbol_cmykepsResurser"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['20BEF08A988D4CF8A646CE8DED4FAA37'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;